id: I1C32288B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T00:15:48+00:00'
last_modified: '2022-06-08T14:37:27.661528+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3414
  title: པཎ་ཆེན་སྐུ་ཕྲེང་རིམ་བྱོན་གྱི་མཛད་རྣམ་ཕྱོགས་སྒྲིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    5BA4:
      image_group_id: I3CN8464
      title: ''
      total_pages: 540
      order: 1
      base_file: 5BA4.txt
    '0260':
      image_group_id: I3CN8465
      title: ''
      total_pages: 706
      order: 2
      base_file: 0260.txt
    BEB3:
      image_group_id: I3CN8466
      title: ''
      total_pages: 922
      order: 3
      base_file: BEB3.txt
    775B:
      image_group_id: I3CN8467
      title: ''
      total_pages: 872
      order: 4
      base_file: 775B.txt
    B812:
      image_group_id: I3CN8468
      title: ''
      total_pages: 738
      order: 5
      base_file: B812.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
